config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controller: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  
  resources :contacts
  resources :products, only: [:show]
  post 'quote', to: 'products#quote'
  get 'checkout', to: 'products#checkout'
  post 'order', to: 'products#order'
  get 'done', to: 'products#done'
  get 'index', to: 'products#index'
  get 'faqs', to: 'pages#faqs'
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/product.rb
class Product < ActiveRecord::Base

end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    
     has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: 
    "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            
            ContactMailer.contact_email(name, email, body).deliver
            
            flash[:success] = "Message sent."
            redirect_to new_contact_path
        else
            flash[:danger] = "Error occured."
            redirect_to new_contact_path
        end
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
    end
    
    def about
    end
    
    def faqs
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index 
        @products = Product.all 
    end 
    
    def show 
        @product = Product.find(params[:id]) 
    end 
    
    def quote 
        # code for UberRUSH shipping quote 
    end 
    
    def checkout
        # code for checkout
    end
    
    def order 
        # code for Stripe charge and UberRUSH delivery creation 
    end
    
    def done 
        # code for confirmation page 
    end 
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_current_user
    
    def new
        # form where user can fill out their own profile
        @user = User.find( params[:user_id] )
        @profile = Profile.new
    end
    
    
     def create
        @user = User.find( params[:user_id] )
        @profile = @user.build_profile(profile_params)
         if @profile.save
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :new
        end
    end
    
    def edit
        @user = User.find( params[:user_id] )
        @profile = @user.profile
    end
    
    def update
        @user = User.find(params[:user_id] )
        @profile = @user.profile
        if @profile.update_attributes(profile_params)
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :edit
        end
    end
    
    private
        def profile_params
            params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :contact_email, :description)
        end
        
        def only_current_user
            @user = User.find( params[:user_id] )
            redirect_to(root_url) unless @user == current_user
        end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_filter :select_plan, only: :new
    
    def create
        super do |resource|
            if params[:plan]
                resource.plan_id = params[:plan]
                resource.save
            end
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @users = User.includes(:profile)
    end
    
    def show
        @user = User.find( params[:id] )
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def job_title_icon
        if @user.profile.job_title == "Independent Buyer"
            "<i class='fa fa-user'></i>".html_safe
        elsif @user.profile.job_title == "Company Representative"
            "<i class='fa fa-user-plus'></i>".html_safe
        elsif @user.profile.job_title == "Store Owner"
            "<i class='fa fa-university'></i>".html_safe
        end
    end
end

app/views/contacts/new.html.erb
<div class="container text-center">
    <p  class="h2">Questions or Comments</p>
    <p class="h3">Are greatly appreciated.</p>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="well text-center">
         <%= form_for @contact do |f| %>
           <div class="form-group">
             <%= f.label :name %>
             <%= f.text_field :name, class:'form-control' %>
           </div>
      
           <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class:'form-control'%>
           </div>
        
           <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class:'form-control' %>
           </div>
           <%= f.submit 'submit', class: 'btn btn-default' %>
           <% end %>
        </div>
    </div>
</div>

<h2 class="text-center">What our customers say</h2>
<div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    <h4>"This company is the best. I am so happy with the result!"<br><span style="font-style:normal;">Michael Roe, Vice President, Comment Box</span></h4>
    </div>
    <div class="item">
      <h4>"One word... WOW!!"<br><span style="font-style:normal;">John Doe, Salesman, Rep Inc</span></h4>
    </div>
    <div class="item">
      <h4>"Could I... BE any more happy with this company?"<br><span style="font-style:normal;">Chandler Bing, Actor, FriendsAlot</span></h4>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/picnicss/6.1.1/picnic.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body class="row">

<nav class="nav navbar-inverse navbar-fixed-top"  role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to root_path, class: 'navbar-brand' do %>
      <i class="fa fa-comments-o" aria-hidden="true"></i>
      ASM - Impex
    <% end %>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Store", index_path %></li>
      <li><%= link_to "Contact Us", new_contact_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <!-- /.sign up / login -->
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-check"></span> Login<span class="caret"></a>
        <ul class="dropdown-menu" role="menu">
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path, method: :get %></li>
            <li><%= link_to "Sign In", new_user_session_path, method: :get %></li>
          <% end %>
          <li role="separator" class="divider"></li>
          <% if user_signed_in? %>
            <% if current_user.profile %>
              <li><%= link_to  "View Your Profile", user_path(current_user) %></li>
              <li><%= link_to "Community", users_path %></li>
              <li><%= link_to "Edit Your Profile", edit_user_profile_path(current_user) %></li>
              <li><%= link_to "My Account", edit_user_registration_path %></li>
            <% else %>
              <%= link_to "Create your Profile", new_user_profile_path(current_user) if current_user %>
            <% end %>
          <% end %>
          <li>><%= link_to "FAQ's", faqs_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  
  <%= yield %>
</div>

<footer class="container-fluid bg-4 text-center">
  <div id="container-footer" class="text-center">
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a><br><br>
  <h1><%= link_to "Contact Us", new_contact_path %></h1>
    <div class="btn-group">
      <!--Facebook-->
      <button type="button" class="btn btn-lg btn-fb"><i class="fa fa-facebook"></i></button>
      <!--Facebook-->
      <button type="button" class="btn btn-lg btn-tw"><i class="fa fa-twitter"></i></button>
      <!--Facebook-->
      <button type="button" class="btn btn-lg btn-ins"><i class="fa fa-instagram"></i></button>
    </div>
  </div>
</footer>

</body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="container text-center">
    <h1>ASM - IMPEX</h1>
    <p><b>Online Store and catalog directory with complete electronic sets and imported textiles.</b></p>
    <p>Nullam porta sapien eu mi efficitur vehicula. <%= link_to "Home", root_path %> 
      <a href="#">
        <span class="glyphicon glyphicon-heart"></span>
      </a></br>
      Nullam a lectus vitae risus sodales pulvinar tempor at risus. <%= link_to "Home", root_path %>
      <a href="#">
        <span class="glyphicon glyphicon-home"></span>
      </a></br>
      Cras eget nisl id odio egestas elementum vitae sit amet orci. <%= link_to "Home", root_path %>
      <a href="#">
        <span class="glyphicon glyphicon-headphones"></span>
      </a></br>
      Cras mattis augue a justo bibendum, in eleifend lectus efficitur. <%= link_to "Home", root_path %> 
      <a href="#">
        <span class="glyphicon glyphicon-tags"></span>
      </a></p>
  </div>
</div></br>

<div class="row">
  <div class="container text-center">
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQN906ZAJ0TFLU85RAjmiwDjq5ONwmsQdJ6_CCTGkinpG_N6le9ww" alt="Apparel">
        <p><strong>Clothing</strong></p>
        <p>Fashion</p>
        <a class="btn" href="/">Search</a>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="http://www.pakthat.co.uk/images-detail/android_tablet_box_withwhite_tablet.jpg" alt="Electronics">
        <p><strong>Electronics</strong></p>
        <p>New</p>
        <a class="btn" href="/">Search</a>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTfQqI4-Yjzvu0uBTdcYR32cRvkkm7U9kh55IoGIxDZMQwazvem" alt="Promo">
        <p><strong>Discounts</strong></p>
        <p>Bundle and Save</p>
        <a class="btn" href="/">Search</a>
      </div>
    </div>
  </div>
</div>

app/views/pages/faqs.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>FAQ's</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="#section1">Home</a></li>
        <li><a href="#section2">Products</a></li>
        <li><a href="#section3">Shipping</a></li>
        <li><a href="#section3">Profile</a></li>
      </ul><br>
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search Blog..">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    </div>

    <div id="section2" class="container-fluid">
        <div class="col-sm-9">
          <h2><small>ASM - Impex</small></h2>
          <hr>
          <h2>Signing In</h2>
          <h5><span class="glyphicon glyphicon-time"></span> Post by Sajj, Jul 27, 2016.</h5>
          <h5><span class="label label-danger">About</span> <span class="label label-primary">Sign In</span></h5><br>
          <p>How to create a unique sign in. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <br><br>
        </div>
    </div>
  
    <div id="section3" class="container-fluid">
        <div class="col-sm-9">      
          <h4><small>RECENT POSTS</small></h4>
          <hr>
          <h2>Order Catalog/Guide</h2>
          <h5><span class="glyphicon glyphicon-time"></span> Post by Sajj, Jul 27, 2016.</h5>
          <h5><span class="label label-success">Lorem</span></h5><br>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <br><br>
        </div>
    </div>
<script>
$(document).ready(function(){
    $('body').scrollspy({target: ".navbar", offset: 50});
});
</script>

app/views/pages/home.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="http://image.shutterstock.com/display_pic_with_logo/4225/4225,1228981736,1/stock-photo-clothing-in-store-22003183.jpg" alt="New York" width="100%" height="400">
        <div class="carousel-caption">
          <h3>Imported textiles and fashion...</h3>
          <p>Great quality, for home to industrial items.</p>
        </div>
      </div>

      <div class="item">
        <img src="http://image.shutterstock.com/display_pic_with_logo/1008791/287393273/stock-photo-headphones-and-phone-depth-of-field-287393273.jpg" alt="Chicago" width="100%" height="400">
        <div class="carousel-caption">
          <h3>Promo</h3>
          <p>Brand new electronics, bundle to recieve discounts.</p>
        </div>
      </div>
    
      <div class="item">
        <img src="http://image.shutterstock.com/display_pic_with_logo/441661/356184749/stock-photo-london-england-december-person-riding-a-hoverboard-on-a-public-footpath-they-are-now-356184749.jpg" alt="Los Angeles" width="100%" height="400">
        <div class="carousel-caption">
          <h3>Sign up to get promotions.</h3>
          <p>Shop any-time, join the promo-Impex club for gret deals.</p>
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel2" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel2" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

<footer>
<div id="modal" class="container-fluid bg-5 text-center">
  <h2><p>Send a Message for more info...</p></h2>
  <p>Shipping Daily</p>
  <h3><p class"text-center"><i class="fa fa-envelope" aria-hidden="true"></i>Asm.impex@yahoo.com</p></h3>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal"><i class="fa fa-location-arrow" aria-hidden="true"></i>Map</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <div class="modal-title"><h4>Shipping Daily</h4><i class="fa fa-mobile" aria-hidden="true"></i></div>
        </div>
        <div class="modal-body">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d105710.97727146861!2d-117.53280967366932!3d34.10876567350707!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c34b8f224409c3%3A0x78cbf3c11829549b!2sFontana%2C+CA!5e0!3m2!1sen!2sus!4v1471075916613" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
     </div> 

  </div>
</div>
</footer><br><br></hr></b>

app/views/products/checkout.html.erb
<div class="row">
	<h1>Shopping Cart</h1>
	
	<div class="shopping-cart">
	
	  <div class="column-labels">
	    <label class="product-image">Image</label>
	    <label class="product-details">Product</label>
	    <label class="product-price">Price</label>
	    <label class="product-quantity">Quantity</label>
	    <label class="product-removal">Remove</label>
	    <label class="product-line-price">Total</label>
	  </div>
	
	  <div class="product">
	    <div class="product-image">
	      <img src="http://s.cdpn.io/3/dingo-dog-bones.jpg">
	    </div>
	    <div class="product-details">
	      <div class="product-title">Dingo Dog Bones</div>
	      <p class="product-description">The best dog bones of all time. Holy crap. Your dog will be begging for these things! I got curious once and ate one myself. I'm a fan.</p>
	    </div>
	    <div class="product-price">12.99</div>
	    <div class="product-quantity">
	      <input type="number" value="2" min="1">
	    </div>
	    <div class="product-removal">
	      <button class="remove-product">
	        Remove
	      </button>
	    </div>
	    <div class="product-line-price">25.98</div>
	  </div>
	
	  <div class="product">
	    <div class="product-image">
	      <img src="http://s.cdpn.io/3/large-NutroNaturalChoiceAdultLambMealandRiceDryDogFood.png">
	    </div>
	    <div class="product-details">
	      <div class="product-title">Nutro™ Adult Lamb and Rice Dog Food</div>
	      <p class="product-description">Who doesn't like lamb and rice? We've all hit the halal cart at 3am while quasi after a night of ipsum in Manhattan. Now it's your dog's turn!</p>
	    </div>
	    <div class="product-price">45.99</div>
	    <div class="product-quantity">
	      <input type="number" value="1" min="1">
	    </div>
	    <div class="product-removal">
	      <button class="remove-product">
	        Remove
	      </button>
	    </div>
	    <div class="product-line-price">45.99</div>
	  </div>
	
	  <div class="totals">
	    <div class="totals-item">
	      <label>Subtotal</label>
	      <div class="totals-value" id="cart-subtotal">71.97</div>
	    </div>
	    <div class="totals-item">
	      <label>Tax (5%)</label>
	      <div class="totals-value" id="cart-tax">3.60</div>
	    </div>
	    <div class="totals-item">
	      <label>Shipping</label>
	      <div class="totals-value" id="cart-shipping">15.00</div>
	    </div>
	    <div class="totals-item totals-item-total">
	      <label>Grand Total</label>
	      <div class="totals-value" id="cart-total">90.57</div>
	    </div>
	  </div>
	      
	      <button class="checkout">Checkout</button>
	
	</div>
</div>

app/views/products/index.html.erb
<div class="jumbotron text-center">
  <div class="container">
      <h1>ASM Impex</h1> 
      <p>We specialize in online-shopping</p>
      <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          Welcome to Asm - Impex
        </button>
        
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Asm - Impex</h4>
              </div>
              <div class="modal-body">
                Welcome to Asm - Impex, an online store specializing in a variety of textiles, electronic promotions, and clothing/home-goods!
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

<div class="flex one three-1000">
    <% @products.each do |product| %>
        <article class="card">
            <img src="<%= product.picture %>">
            <footer>
                <h3><%= product.title %></h3>
                <%= link_to "Buy", product_path(product), class: "btn btn-default" %>
            </footer>
        </article>
    <% end %>
</div>

app/views/products/show.html.erb
<div class="flex one two-1000">
    <div class="product-image">
        <img src="<%= @product.picture %>" />
    </div>
  <div>
      <h1><%= @product.title %></h1>
    <p>
        <%= @product.description %>
    </p>
    
    <h2><%= number_to_currency(@product.price) %></h2>
    <hr/>
    
    <h3>Instant Shipping</h3>
    <img src="https://s31.postimg.org/cjyo11eqj/uber_rush.png" class="logo"/>
        <small>UberRUSH is an on-demand delivery network powered by Uber. Once your order is picked up, you’ll receive a text message with a link to track your delivery in real time on the map. So you always know exactly when it will arrive. </small> </p>
    </p>

    <%= link_to "Cart", root_path, class: "btn btn-default" %>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    
     <div class="form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :job_title %>
        <%= f.select :job_title, ['Independent Buyer', 'Company Representative', 'Store Owner'], {}, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.submit "Update Profile", class: 'btn btn-default' %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit Your Profile</h1>
        <p class="text-center">Update your personal info...</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron bg-2">
    <div class="container-fluid text-center">
      <h2 class="margin">ASM - Impex</h2>
      <p>World-Class Industry specializing in electronics, clothing, materials, imported textiles, and much more...</p>
        <img src="http://41.media.tumblr.com/0515719099389a401818068d800450ed/tumblr_inline_nt08nbCAz81rjic88_1280.jpg" class="img-circle" alt="Cinque Terre" width="304" height="236">
        <h3>About Me<br><i class="fa fa-bars" aria-hidden="true"></i></h3>
    </div>
</div>

<div class="col-md-6 col-md-offset-3">
  <h1 class="margin text-center"><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1><br>
  <div class="row">
    <div class="col-md-3 text-center">
      
    </div>
  </div>
  <div class="row bg-3">
    <div class="col-md-4 text-center">
        <h3>My Bio</h3>
      <%= @user.profile.description %>
    </div>
    <div class="col-md-4 text-center">
        <h3>Title</h3>
      <span class="job-title-icon"><%= job_title_icon %></span><%= @user.profile.job_title %>
    </div>  
    <div class="col-md-4 text-center">
        <h3>Email</h3>
      <%= @user.profile.contact_email %>
    </div>
  </div>
</div>

<div class="col-md-4 col-md-offset-4">
  <h2 class="margin text-center">ASM ™ Impex Community</h2>
      <div class="container-fluid text-center">
      <%= link_to "Visit the Community", users_path, class: 'btn btn-default' %>
    </div>
</div>